from fencing import maybeFencedString, maybeFencedLatex, maybeFenced
from binary_operation import BinaryOperation
from associative_operation import AssociativeOperation
from operation_over_instances import OperationOverInstances, InstanceSubstitutionException
